// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMrAB-lNRDKl5TsbvzJJwM6yl_UF35d0',
    appId: '1:997509411455:web:54a3bcdb4c538a5cf6054a',
    messagingSenderId: '997509411455',
    projectId: 'finalproject-8fba1',
    authDomain: 'finalproject-8fba1.firebaseapp.com',
    databaseURL: 'https://finalproject-8fba1-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-8fba1.firebasestorage.app',
    measurementId: 'G-XFKF6T22DS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcbgQ9QCKlGfnbGjAczIkmGYy_cCAmjy4',
    appId: '1:997509411455:ios:9b33d3ca30747e56f6054a',
    messagingSenderId: '997509411455',
    projectId: 'finalproject-8fba1',
    databaseURL: 'https://finalproject-8fba1-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-8fba1.firebasestorage.app',
    iosBundleId: 'com.example.finalprojectAdmin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcbgQ9QCKlGfnbGjAczIkmGYy_cCAmjy4',
    appId: '1:997509411455:ios:9b33d3ca30747e56f6054a',
    messagingSenderId: '997509411455',
    projectId: 'finalproject-8fba1',
    databaseURL: 'https://finalproject-8fba1-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-8fba1.firebasestorage.app',
    iosBundleId: 'com.example.finalprojectAdmin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDctALHEpLovpvHFefeOKYASWglKrjc4o',
    appId: '1:997509411455:android:0c09421c50c4dd4ff6054a',
    messagingSenderId: '997509411455',
    projectId: 'finalproject-8fba1',
    databaseURL: 'https://finalproject-8fba1-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-8fba1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaMrAB-lNRDKl5TsbvzJJwM6yl_UF35d0',
    appId: '1:997509411455:web:664febe0f56b5bf2f6054a',
    messagingSenderId: '997509411455',
    projectId: 'finalproject-8fba1',
    authDomain: 'finalproject-8fba1.firebaseapp.com',
    databaseURL: 'https://finalproject-8fba1-default-rtdb.firebaseio.com',
    storageBucket: 'finalproject-8fba1.firebasestorage.app',
    measurementId: 'G-2SZ71E2YTD',
  );

}